from enum import StrEnum


class UserRole(StrEnum):
    SUPER_ADMIN = "SUPER_ADMIN"
    RH = "RH"
    GESTOR_OBRA = "GESTOR_OBRA"
    SUPERVISOR = "SUPERVISOR"
    FUNCIONARIO = "FUNCIONARIO"


class EmployeeStatus(StrEnum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    ON_LEAVE = "ON_LEAVE"


class PunchType(StrEnum):
    ENTRY = "ENTRY"
    LUNCH_OUT = "LUNCH_OUT"
    LUNCH_IN = "LUNCH_IN"
    EXIT = "EXIT"


class AttendanceStatus(StrEnum):
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    MANUAL_REVIEW = "MANUAL_REVIEW"
    OFFLINE_PENDING = "OFFLINE_PENDING"


class DeviceStatus(StrEnum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    MAINTENANCE = "MAINTENANCE"


class FraudType(StrEnum):
    PRINTED_PHOTO = "PRINTED_PHOTO"
    PHONE_SCREEN = "PHONE_SCREEN"
    VIDEO_REPLAY = "VIDEO_REPLAY"
    MULTIPLE_FACES = "MULTIPLE_FACES"
    LOW_LIVENESS = "LOW_LIVENESS"
    LOW_SIMILARITY = "LOW_SIMILARITY"
    OUT_OF_GEOFENCE = "OUT_OF_GEOFENCE"
    UNKNOWN_FACE = "UNKNOWN_FACE"


class AlertSeverity(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class EnrollmentPose(StrEnum):
    FRONTAL = "FRONTAL"
    TURN_LEFT = "TURN_LEFT"
    TURN_RIGHT = "TURN_RIGHT"
    LOOK_UP = "LOOK_UP"
    FRONTAL_FINAL = "FRONTAL_FINAL"


class EnrollmentSessionStatus(StrEnum):
    ACTIVE = "ACTIVE"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    EXPIRED = "EXPIRED"


class EnrollmentState(StrEnum):
    WAITING_FACE = "WAITING_FACE"
    ALIGN_FACE = "ALIGN_FACE"
    MOVE_CLOSER = "MOVE_CLOSER"
    MOVE_AWAY = "MOVE_AWAY"
    IMPROVE_LIGHTING = "IMPROVE_LIGHTING"
    LOOK_FORWARD = "LOOK_FORWARD"
    TURN_LEFT = "TURN_LEFT"
    TURN_RIGHT = "TURN_RIGHT"
    LOOK_UP = "LOOK_UP"
    HOLD_STILL = "HOLD_STILL"
    CAPTURED = "CAPTURED"
    DUPLICATE_CAPTURE = "DUPLICATE_CAPTURE"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
